batchsize: 32
checkpoint_path: model/model_real.pt
dct_stride: 76
dct_stride_percent: 0.3
dct_width: 256
embed_dim: 256
embed_loss_weight: 0.0001
epochs: 2000
fix_embedding: false
init_embedding: true
lr: 0.01
patch_n: 15
real_data_path: dataset/real
scheduler_gamma: 0.95
scheduler_step: 20
